
---
applicationUrl: https://console.unbxd.io
baseUrl: https://console-uk.unbxd.io
services:
  - name: solr
    url: http://docker-fsd2.unbxd.io:8900
  - name: brewer
    url: http://docker-fsd2.unbxd.io:8901
  - name: groot
    url: http://docker-fsd2.unbxd.io:8903
  - name: gimli
    url: http://docker-fsd2.unbxd.io:8904
  - name: asterix
    url: http://docker-fsd2.unbxd.io:6339
  - name: feed
    url: http://feed-uk.unbxd.io
  - name: ether
    url: http://docker-fsd2.unbxd.io:2205
  - name: mysql
    url: docker-fsd.unbxd.io:3306
  - name: console
    url: https://console-uk.unbxd.io

sites:
  - siteKey: ss-unbxd-auk-FireflinkTestSiteUK39111733818004
    apiKey: 9f336905808a6a5f99cc25f0f1e98db5
    secretKey: 77bc8af8b94402e760ced06324a0a218
    statusById: ebaf259a-bcea-4c0d-99b6-1ea4957e006a
    siteId: 1502
    region: UK Customer Sites
    id: 1
  - siteKey: ss-unbxd-auk-FireflinkTestSiteUK39111733818004
    apiKey: 9f336905808a6a5f99cc25f0f1e98db5
    secretKey: 77bc8af8b94402e760ced06324a0a218
    statusById: ebaf259a-bcea-4c0d-99b6-1ea4957e006a
    siteId: 1521
    region: UK Customer Sites
    id: 2

users:
  - id: 1
    email: AutomationSeleniumUK@yopmail.com
    password: Password@123
    deleteSiteSsoIdKeyValue: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjpudWxsLCJleHBpcnkiOiIyMDIxLTA0LTEzIDA5OjIxOjE2IFVUQyIsImVtYWlsIjoicHJvZGF6MUB5b3BtYWlsLmNvbSIsInJlZ2lvbnMiOnsidXMiOnsicmVmX3VzZXJfaWQiOjgxODAwfSwiYXUiOnsicmVmX3VzZXJfaWQiOjk0M30sInVrIjp7InJlZl91c2VyX2lkIjo5MjN9LCJzZyI6eyJyZWZfdXNlcl9pZCI6MTE2NH19fQ.nSwcIlR1i9XfKgxCi0yQxbGmipapcTSM4OROoFgyWR8

  - id: 2
    email: AutomationSeleniumUK@yopmail.com
    password: Password@123

