
---
applicationUrl: https://console.unbxd.io
baseUrl: https://console-g-anz.unbxd.io
services:
  - name: solr
    url: http://docker-fsd2.unbxd.io:8900
  - name: brewer
    url: http://docker-fsd2.unbxd.io:8901
  - name: groot
    url: http://docker-fsd2.unbxd.io:8903
  - name: gimli
    url: http://docker-fsd2.unbxd.io:8904
  - name: asterix
    url: http://docker-fsd2.unbxd.io:6339
  - name: feed
    url: http://feed-anz.unbxd.io
  - name: ether
    url: http://docker-fsd2.unbxd.io:2205
  - name: mysql
    url: docker-fsd.unbxd.io:3306
  - name: console
    url: https://console-anz.unbxd.io


sites:
  - siteKey: ss-unbxd-ganz-UnbxdQaTestSite-MerchConsole18641758784126
    apiKey: 873da59e43c064caa1147306cb11320f
    secretKey: 7b2ddefbf04225b889190828b4d0181d
    statusById: 84b5b88e-fc40-454f-baf8-12b710bf711c
    siteId: 211
    region: AZ Customer Sites
    id: 1
  - siteKey: ss-unbxd-ganz-unbxd-QATest-site-ManageSelenium18641758479079
    apiKey: d8b7eec24a5a98030dd6c4022f4997e8
    secretKey: 28f92438137e155225abf6066d5c03c3
    statusById: 84b5b88e-fc40-454f-baf8-12b710bf711c
    siteId: 204
    region: AZ Customer Sites
    id: 2

users:
  - id: 1
    email: AutomationSeleniumAnz@yopmail.com
    password: Password@123
    deleteSiteSsoIdKeyValue: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjpudWxsLCJleHBpcnkiOiIyMDIxLTA0LTEzIDA5OjIxOjE2IFVUQyIsImVtYWlsIjoicHJvZGF6MUB5b3BtYWlsLmNvbSIsInJlZ2lvbnMiOnsidXMiOnsicmVmX3VzZXJfaWQiOjgxODAwfSwiYXUiOnsicmVmX3VzZXJfaWQiOjk0M30sInVrIjp7InJlZl91c2VyX2lkIjo5MjN9LCJzZyI6eyJyZWZfdXNlcl9pZCI6MTE2NH19fQ.nSwcIlR1i9XfKgxCi0yQxbGmipapcTSM4OROoFgyWR8

  - id: 2
    email: AutomationSeleniumAnz@yopmail.com
    password: Password@123

