
---
applicationUrl: https://console.unbxd.io
baseUrl: https://console-nam.unbxd.io
services:
  - name: solr
    url: http://docker-fsd2.unbxd.io:8900
  - name: brewer
    url: http://docker-fsd2.unbxd.io:8901
  - name: groot
    url: http://docker-fsd2.unbxd.io:8903
  - name: gimli
    url: http://docker-fsd2.unbxd.io:8904
  - name: asterix
    url: http://docker-fsd2.unbxd.io:6339
  - name: feed
    url: http://feed.unbxd.io
  - name: ether
    url: http://docker-fsd2.unbxd.io:2205
  - name: mysql
    url: docker-fsd.unbxd.io:3306
  - name: console
    url: https://console-nam.unbxd.io

sites:
  - siteKey: ss-unbxd-useHybris819231645093575
    apiKey: 35a1313b208be19f89b5e6771bf407c6
    secretKey: ae585401326b90c43004166e7a419dfd
    statusById: 40caba10-6fc4-4ad9-903a-a9cc073f9e70
    siteId: 654121
    region: US Customer Sites
    id: 1
  - siteKey: ss-unbxd-prodUseprod813191655213431
    apiKey: 57cba2e3c065cb78a903d1510f7941af
    secretKey: 63b0f193ae481ca36af2638919ade71f
    statusById: 4aefbb7d-32b4-4aba-bb9a-539f5c58da7f
    siteId: 654117
    region: AU Customer Sites
    id: 2

users:
  - id: 1
    email: newusering1@yopmail.com
    password: Password@123
    deleteSiteSsoIdKeyValue: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjpudWxsLCJleHBpcnkiOiIyMDIxLTA0LTEzIDA5OjE1OjU0IFVUQyIsImVtYWlsIjoiYXV0b21hdGlvbnByb2RAeW9wbWFpbC5jb20iLCJyZWdpb25zIjp7InVzIjp7InJlZl91c2VyX2lkIjo4MTMyMn19fQ.s3YooZ0t7P877_U7VNv1Q-w-Cab0iJKUsBKmIOekG4s

  - id: 2
    email: newusering1@yopmail.com
    password: Password@123